import React, { useState } from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image } from "react-native";
import { ExternalLink, ChevronRight } from "lucide-react-native";
import colors from "@/constants/colors";

type ArticleCategory = "basics" | "tips" | "science" | "impact";

interface Article {
  id: string;
  title: string;
  description: string;
  category: ArticleCategory;
  imageUrl: string;
  content: string;
}

const articles: Article[] = [
  {
    id: "basics-1",
    title: "What is a Carbon Footprint?",
    description: "Learn about carbon footprints and why they matter",
    category: "basics",
    imageUrl: "https://images.unsplash.com/photo-1569163139599-0f4517e36f31?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    content: `A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.

The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons.

To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per person needs to drop to under 2 tons by 2050.

Lowering individual carbon footprints from 16 tons to 2 tons doesn't happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights, and line drying our clothes, we can start making a big difference.`,
  },
  {
    id: "tips-1",
    title: "10 Ways to Reduce Your Carbon Footprint",
    description: "Simple actions you can take today",
    category: "tips",
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    content: `Here are 10 effective ways to reduce your carbon footprint:

1. Eat less meat and dairy: Animal products are responsible for a large portion of greenhouse gas emissions.

2. Drive less: Walk, bike, carpool, or use public transportation whenever possible.

3. Reduce air travel: One long-haul flight can produce more CO2 than some people generate in a year.

4. Use energy-efficient appliances: Look for ENERGY STAR certified products.

5. Switch to renewable energy: Consider solar panels or choose a green energy provider.

6. Reduce, reuse, recycle: Follow this hierarchy to minimize waste.

7. Save water: Take shorter showers and fix leaky faucets.

8. Buy local and seasonal food: This reduces transportation emissions.

9. Unplug electronics: Many devices use power even when turned off.

10. Plant trees: Trees absorb CO2 and provide numerous environmental benefits.`,
  },
  {
    id: "science-1",
    title: "The Science of Climate Change",
    description: "Understanding the basics of climate science",
    category: "science",
    imageUrl: "https://images.unsplash.com/photo-1581093458791-9f3c3e4f7b41?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    content: `Climate change refers to long-term shifts in temperatures and weather patterns. These shifts may be natural, but since the 1800s, human activities have been the main driver of climate change, primarily due to the burning of fossil fuels like coal, oil, and gas, which produces heat-trapping gases.

Greenhouse gases act like a blanket wrapped around the Earth, trapping the sun's heat and raising temperatures. Examples include carbon dioxide, methane, nitrous oxide, and water vapor.

The effects of climate change include:
- Rising temperatures
- More severe weather events
- Rising sea levels
- Changing wildlife populations and habitats
- Increased health risks

The scientific consensus is clear: climate change is real, and human activities are the primary cause. The Intergovernmental Panel on Climate Change (IPCC), which includes more than 1,300 scientists from around the world, forecasts a temperature rise of 2.5 to 10 degrees Fahrenheit over the next century.`,
  },
  {
    id: "impact-1",
    title: "University Students and Climate Impact",
    description: "How students can lead the way to a sustainable future",
    category: "impact",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    content: `University students are uniquely positioned to drive climate action:

Campus Impact:
- The average university student generates 3-5 tons of CO2 per year through campus activities
- Housing, transportation, and food choices make up the majority of a student's carbon footprint
- Digital activities, including streaming and cloud storage, contribute approximately 0.25 tons annually

Leadership Opportunities:
- Student-led sustainability initiatives have reduced campus emissions by up to 30% at leading universities
- Green campus movements have successfully advocated for institutional divestment from fossil fuels
- Research shows that sustainability habits formed during university years often persist throughout life

Taking Action:
- Join or start a sustainability club on campus
- Advocate for renewable energy and sustainable food options in dining halls
- Choose coursework that incorporates sustainability principles
- Participate in research projects addressing climate solutions
- Use your education to develop innovative approaches to climate challenges

As future leaders, your choices today will shape climate policy and action for decades to come.`,
  },
  {
    id: "basics-2",
    title: "Carbon Footprint Calculation Methods",
    description: "How carbon emissions are measured and calculated",
    category: "basics",
    imageUrl: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    content: `Carbon footprint calculations involve measuring the greenhouse gas emissions associated with activities, products, or services. Here's how it works:

Direct vs. Indirect Emissions:
- Direct emissions come from sources you control (e.g., your car's exhaust)
- Indirect emissions result from your activities but occur elsewhere (e.g., emissions from producing electricity you use)

Calculation Methods:
1. Life Cycle Assessment (LCA): Tracks emissions through a product's entire life cycle
2. Greenhouse Gas Protocol: Divides emissions into Scope 1 (direct), Scope 2 (energy), and Scope 3 (value chain)
3. Carbon Calculators: Simplified tools that estimate emissions based on lifestyle factors

Common Units:
- Carbon dioxide equivalent (CO2e): Standardizes different greenhouse gases into a single unit
- Metric tons (or kilograms) of CO2e: The standard measurement unit

Accuracy Considerations:
- Calculations are estimates with varying degrees of precision
- More detailed data inputs generally yield more accurate results
- Regular updates to calculation methods reflect evolving science

This app uses standardized emission factors from governmental and scientific databases to estimate your carbon footprint based on your reported activities.`,
  },
];

export default function LearnScreen() {
  const [selectedCategory, setSelectedCategory] = useState<ArticleCategory | "all">("all");
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);

  const filteredArticles = selectedCategory === "all"
    ? articles
    : articles.filter(article => article.category === selectedCategory);

  const renderArticleList = () => (
    <>
      <View style={styles.header}>
        <Text style={styles.title}>Learn</Text>
        <Text style={styles.subtitle}>
          Explore articles about carbon footprints and sustainability
        </Text>
      </View>
      
      <View style={styles.categoriesContainer}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          <TouchableOpacity
            style={[
              styles.categoryButton,
              selectedCategory === "all" && styles.selectedCategoryButton,
            ]}
            onPress={() => setSelectedCategory("all")}
            testID="category-all"
          >
            <Text
              style={[
                styles.categoryText,
                selectedCategory === "all" && styles.selectedCategoryText,
              ]}
            >
              All
            </Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[
              styles.categoryButton,
              selectedCategory === "basics" && styles.selectedCategoryButton,
            ]}
            onPress={() => setSelectedCategory("basics")}
            testID="category-basics"
          >
            <Text
              style={[
                styles.categoryText,
                selectedCategory === "basics" && styles.selectedCategoryText,
              ]}
            >
              Basics
            </Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[
              styles.categoryButton,
              selectedCategory === "tips" && styles.selectedCategoryButton,
            ]}
            onPress={() => setSelectedCategory("tips")}
            testID="category-tips"
          >
            <Text
              style={[
                styles.categoryText,
                selectedCategory === "tips" && styles.selectedCategoryText,
              ]}
            >
              Tips
            </Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[
              styles.categoryButton,
              selectedCategory === "science" && styles.selectedCategoryButton,
            ]}
            onPress={() => setSelectedCategory("science")}
            testID="category-science"
          >
            <Text
              style={[
                styles.categoryText,
                selectedCategory === "science" && styles.selectedCategoryText,
              ]}
            >
              Science
            </Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[
              styles.categoryButton,
              selectedCategory === "impact" && styles.selectedCategoryButton,
            ]}
            onPress={() => setSelectedCategory("impact")}
            testID="category-impact"
          >
            <Text
              style={[
                styles.categoryText,
                selectedCategory === "impact" && styles.selectedCategoryText,
              ]}
            >
              Impact
            </Text>
          </TouchableOpacity>
        </ScrollView>
      </View>
      
      <View style={styles.articlesContainer}>
        {filteredArticles.map((article) => (
          <TouchableOpacity
            key={article.id}
            style={styles.articleCard}
            onPress={() => setSelectedArticle(article)}
            testID={`article-${article.id}`}
          >
            <Image
              source={{ uri: article.imageUrl }}
              style={styles.articleImage}
            />
            <View style={styles.articleContent}>
              <Text style={styles.articleTitle}>{article.title}</Text>
              <Text style={styles.articleDescription} numberOfLines={2}>
                {article.description}
              </Text>
              <View style={styles.articleFooter}>
                <Text style={styles.articleCategory}>
                  {article.category.charAt(0).toUpperCase() + article.category.slice(1)}
                </Text>
                <ChevronRight size={16} color="#666" />
              </View>
            </View>
          </TouchableOpacity>
        ))}
      </View>
    </>
  );

  const renderArticleDetail = () => {
    if (!selectedArticle) return null;
    
    return (
      <View style={styles.articleDetailContainer}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => setSelectedArticle(null)}
          testID="back-button"
        >
          <Text style={styles.backButtonText}>← Back to Articles</Text>
        </TouchableOpacity>
        
        <Image
          source={{ uri: selectedArticle.imageUrl }}
          style={styles.articleDetailImage}
        />
        
        <Text style={styles.articleDetailTitle}>{selectedArticle.title}</Text>
        
        <View style={styles.articleDetailMeta}>
          <Text style={styles.articleDetailCategory}>
            {selectedArticle.category.charAt(0).toUpperCase() + selectedArticle.category.slice(1)}
          </Text>
        </View>
        
        <Text style={styles.articleDetailContent}>
          {selectedArticle.content}
        </Text>
        
        <TouchableOpacity style={styles.externalLinkButton}>
          <ExternalLink size={16} color={colors.primary} />
          <Text style={styles.externalLinkText}>Learn more online</Text>
        </TouchableOpacity>
      </View>
    );
  };

  return (
    <ScrollView 
      style={styles.container} 
      contentContainerStyle={styles.contentContainer}
      testID="learn-screen"
    >
      {selectedArticle ? renderArticleDetail() : renderArticleList()}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: colors.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: "#666",
  },
  categoriesContainer: {
    marginBottom: 20,
  },
  categoryButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: "#F5F5F5",
    marginRight: 8,
  },
  selectedCategoryButton: {
    backgroundColor: colors.primary,
  },
  categoryText: {
    fontSize: 14,
    color: "#666",
  },
  selectedCategoryText: {
    color: "#FFFFFF",
    fontWeight: "600" as const,
  },
  articlesContainer: {
    flex: 1,
  },
  articleCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  articleImage: {
    width: "100%",
    height: 160,
  },
  articleContent: {
    padding: 16,
  },
  articleTitle: {
    fontSize: 18,
    fontWeight: "600" as const,
    color: colors.text,
    marginBottom: 8,
  },
  articleDescription: {
    fontSize: 14,
    color: "#666",
    marginBottom: 12,
  },
  articleFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  articleCategory: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600" as const,
  },
  
  // Article detail styles
  articleDetailContainer: {
    flex: 1,
  },
  backButton: {
    marginBottom: 16,
  },
  backButtonText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: "600" as const,
  },
  articleDetailImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginBottom: 16,
  },
  articleDetailTitle: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: colors.text,
    marginBottom: 8,
  },
  articleDetailMeta: {
    flexDirection: "row",
    marginBottom: 16,
  },
  articleDetailCategory: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600" as const,
  },
  articleDetailContent: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.text,
    marginBottom: 24,
  },
  externalLinkButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#F5F5F5",
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  externalLinkText: {
    marginLeft: 8,
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600" as const,
  },
});